<?php
function sum_menu() {
  $items['sum'] = array(
      'title' => 'Calculate Sum',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('sum_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
  );
  $items['success'] = array(
      'title' => 'Success',
      'page callback' => 'sum_success',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
  );
  return $items;
